print("Nama : Arrijal Abdul Kholik")
print("NIM : 0110223043")
print("Rombel : TI01")
print("Alamat : Jl Mahakam No78 Rt02 Rw09 Mampang Pancoran mas")
print()
print("Nama : Fahdan Zulfa Alsauqi")
print("NNIM : 0110223040")
print("Rombel : TI01")
print("Alamat : Kp Lanbau Rt03 Rw10 Karang Asem Barat Kec Citeureup Bogor")
print()
print("penjumlahan"); print("5+2"); print("5+2")
print()
print("pengurangan"); print("5-2"); print("5-2")
print()
print("perkalian"); print("5*5"); print("5*5")
print()
print("pembagian"); print("4/2"); print("4/2")